Ges_Ecole/flaskges_ecole/classes/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskges_ecole import db
from flaskges_ecole.models import Classe, Eleve, classe_eleves
from flaskges_ecole.classes.forms import ClasseForm, SearchNomClassSelectForm, UpdateClasseForm

classes = Blueprint('classes', __name__)

@classes.route('/classe/new', methods=['POST', 'GET'])
@login_required
def new_classe():
    form = ClasseForm()
    if form.validate_on_submit():
       classes = Classe(nom_classe=form.nom_classe.data)
       db.session.add(classes)
       db.session.commit()
       flash('Your classe has been created !','success')
       return redirect(url_for('classes.new_classe'))

    clas = Classe.query.all()
    return render_template('parametres/new_classe.html', form=form, title='New Classe', clas=clas)

@classes.route('/classe/<int:classe_id>/update', methods=['POST', 'GET'])
def update_classe(classe_id):
    classe = Classe.query.get_or_404(classe_id)
    form = UpdateClasseForm()
    if form.validate_on_submit():
       classe.nom_classe = form.nom_classe.data
       db.session.commit()
       flash('Your classe has been updated !', 'success')
       return redirect(url_for('classes.new_classe'))
    elif request.method == 'GET':
      form.nom_classe.data = classe.nom_classe

    return render_template('parametres/show_classe.html', classe=classe, title='Show Classe',form=form)



@classes.route('/classe/<int:classe_id>/delete', methods=['POST'])
@login_required
def delete_classe(classe_id):
    classe = Classe.query.get_or_404(classe_id)
    db.session.delete(classe)
    db.session.commit()
    flash('Your classe has been deleted !', 'success')
    return redirect(url_for('classes.new_classe'))

@classes.route('/search/name_classe/liste_eleve', methods=['GET', 'POST'])
@login_required
def search_name_classe():
    form = SearchNomClassSelectForm()
    if form.validate_on_submit():
        nom_classe=form.nom_classe.data
        classes = Classe.query.join(classe_eleves).\
                               join(Eleve).\
                               filter(
                                 (classe_eleves.c.classe_id == Classe.id)
                               & (classe_eleves.c.eleve_id == Eleve.id)
                                ).filter(Classe.nom_classe == nom_classe).all()
        if classes:
          return render_template('eleves/show_liste_evele_inscrit.html', nom_classe=nom_classe, classes=classes)
        else:
          flash('Oups ! Pas d\'eleve inscrit dans cette classe', 'danger')

    classes = Classe.query.all()
    return render_template('parametres/search_name_classe.html', form=form, title='Search Name Classe', classes=classes, legend='Search Name Classe')

Ges_Ecole/flaskges_ecole/templates/parametres/new_classe.html
{% extends 'layouts/master.html' %}

{% block content %}
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-md-4" style="padding-top:20px;">
      <div class="content-section" style="height: 240px;">
        {% include 'layouts/partials/_card_left.html' %}
      </div>
    </div>
    <div class="col-md-8" style="padding-top:20px;">

        <div class="card" style="width: 750px;">
          <div class="card-header">Adding Class </div><br>
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#ajoutClasse"style="width: 20%;margin:10px;"> New Classe
            </button><br>
            <form method="post" action="">
              {{ form.hidden_tag() }}
              <!-- Modal -->
                <div class="modal fade" id="ajoutClasse" tabindex="-1" role="dialog"              aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">
                            Adding class</h5>
                        <button type="button" class="close" data-dismiss="modal"
                                aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        <div class="row">
                          <div class="form-group col-md-10">
                            {{ form.nom_classe.label(class="form-control-label") }}
                            {% if form.nom_classe.errors %}
                              {{ form.nom_classe(class="form-control form-control-lg is-invalid") }}
                              <div class="invalid-feedback">
                                {% for error in form.nom_classe.errors  %}
                                  <span> {{ error }} </span>
                                {% endfor %}
                              </div>
                            {% else %}
                              {{ form.nom_classe(class="form-control form-control-lg") }}
                            {% endif %}
                          </div>
                        </div><br>
                          <div class="form-group" style="text-align:center">
                              {{ form.submit(class="btn btn-outline-info ") }}
                          </div>
                      </div>
                    </div>
                  </div>
                </div>
              <!-- end Modal -->
            </form>
            <div class="row container-fluid" >
              <table class="table table-bordered text-center" style="margin-left: 5%">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nom Classe</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                  {% set count = [1] %}
                  {% for classe in clas %}
                    <tr>
                       <th scope="row">{{ count }}</th>
                       <td>{{ classe.nom_classe }}</td>
                       <td>
                         <div class="row">
                          <div class="col-md-6">
                            <a href="{{ url_for('classes.update_classe', classe_id=classe.id) }}">
                               <button type="button" class="btn btn-info btn-sm m-1" >
                               Update</button>
                            </a>
                          </div>
                          <div class="col-md-6">
                            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal"> Delete</button>
                            <!-- Modal -->
                            <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                              <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <h5 class="modal-title" id="deleteModalLabel">Delete Post ?</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                      <span aria-hidden="true">&times;</span>
                                    </button>
                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <form action="{{  url_for('classes.delete_classe', classe_id=classe.id) }}" method="POST">
                                      <input type="submit" class="btn btn-danger" value="Delete">
                                    </form>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <!--End Modal -->

                          </div>
                        </div>

                       </td>
                      {% if count.append(count.pop() + 1) %}{% endif %}
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
        </div>
      </div>

  </div>
</div>


{% endblock %}

Ges_Ecole/flaskges_ecole/templates/parametres/search_name_classe.html
{% extends 'layouts/master.html' %}

{% block content %}
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-md-4" style="padding-top:20px;">
      <div class="content-section" style="height: 240px;">
        {% include 'layouts/partials/_card_left.html' %}
      </div>
    </div>
    <div class="col-md-8" style="padding-top:20px;">
      <div class="card" style="width: 750px;">

        <div class="card-body">
           <form method="POST" action="">
              {{ form.hidden_tag() }}
              <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                  <div class="row container-fluid">
                  <div class="col-md-8">
                    <div class="form-group">
                      {{ form.nom_classe.label(class="form-control-label") }}
                      <select class="custom-select" {{ form.nom_classe(class="form-control form-control-lg") }} >
                      <option value="" selected="selected">Indiquer le nom de la classe?</option>
                        {% for classe in classes %}
                          <option value="{{ classe.nom_classe}}">{{ classe.nom_classe }}</option>
                        {% endfor %}
                      </select>
                    </div>
                  </div>
                  <div class="col-md-4"><br>
                     <div class="form-group" style="text-align:center;">
                        {{ form.submit(class="btn btn-outline-info") }}
                    </div>
                  </div>
                </div>
            </fieldset><br>
          </form>
       </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

Ges_Ecole/flaskges_ecole/templates/parametres/show_classe.html
{% extends 'layouts/master.html' %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-4" style="padding-top:20px;">
      <div class="content-section" style="height: 240px;">
        {% include 'layouts/partials/_card_left.html' %}
      </div>
    </div>
    <div class="col-md-8" style="padding-top:20px;">
      <div class="content-section" style="width: 600px;">
          <!-- FORM HERE -->
          <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
              <legend class="border-bottom mb-4">Update Classe</legend>
                <div class="form-group">
                  {{ form.nom_classe.label(class="form-control-label") }}
                  {% if form.nom_classe.errors %}
                    {{ form.nom_classe(class="form-control form-control-lg is-invalid") }}
                      <div class="invalid-feedback">
                        {% for error in form.nom_classe.errors  %}
                          <span> {{ error }} </span>
                        {% endfor %}
                      </div>
                  {% else %}
                   {{ form.nom_classe(class="form-control form-control-lg") }}
                  {% endif %}
                 </div>
              </fieldset>
              <div class="form-group" style="text-align:center">
                {{ form.submit(class="btn btn-outline-info") }}
              </div>
          </form>
        <!--end FORM HERE -->
        </div>
     </div>
   </div>
 </div>
{% endblock %}