Ges_Ecole/flaskges_ecole/classes/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskges_ecole import db
from flaskges_ecole.models import Classe, Eleve, classe_eleves
from flaskges_ecole.classes.forms import ClasseForm, SearchNomClassSelectForm, UpdateClasseForm

classes = Blueprint('classes', __name__)

@classes.route('/classe/new', methods=['POST', 'GET'])
@login_required
def new_classe():
    form = ClasseForm()
    if form.validate_on_submit():
       classes = Classe(nom_classe=form.nom_classe.data)
       db.session.add(classes)
       db.session.commit()
       flash('Your classe has been created !','success')
       return redirect(url_for('classes.new_classe'))

    clas = Classe.query.all()
    return render_template('parametres/new_classe.html', form=form, title='New Classe', clas=clas)

@classes.route('/classe/<int:classe_id>/update', methods=['POST', 'GET'])
def update_classe(classe_id):
    classe = Classe.query.get_or_404(classe_id)
    form = UpdateClasseForm()
    if form.validate_on_submit():
       classe.nom_classe = form.nom_classe.data
       db.session.commit()
       flash('Your classe has been updated !', 'success')
       return redirect(url_for('classes.new_classe'))
    elif request.method == 'GET':
      form.nom_classe.data = classe.nom_classe

    return render_template('parametres/show_classe.html', classe=classe, title='Show Classe',form=form)



@classes.route('/classe/<int:classe_id>/delete', methods=['POST'])
@login_required
def delete_classe(classe_id):
    classe = Classe.query.get_or_404(classe_id)
    db.session.delete(classe)
    db.session.commit()
    flash('Your classe has been deleted !', 'success')
    return redirect(url_for('classes.new_classe'))

@classes.route('/search/name_classe/liste_eleve', methods=['GET', 'POST'])
@login_required
def search_name_classe():
    form = SearchNomClassSelectForm()
    if form.validate_on_submit():
        nom_classe=form.nom_classe.data
        classes = Classe.query.join(classe_eleves).\
                               join(Eleve).\
                               filter(
                                 (classe_eleves.c.classe_id == Classe.id)
                               & (classe_eleves.c.eleve_id == Eleve.id)
                                ).filter(Classe.nom_classe == nom_classe).all()
        if classes:
          return render_template('eleves/show_liste_evele_inscrit.html', nom_classe=nom_classe, classes=classes)
        else:
          flash('Oups ! Pas d\'eleve inscrit dans cette classe', 'danger')

    classes = Classe.query.all()
    return render_template('parametres/search_name_classe.html', form=form, title='Search Name Classe', classes=classes, legend='Search Name Classe')

Ges_Ecole/flaskges_ecole/eleves/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskges_ecole import db
from flaskges_ecole.models import Eleve, Classe
from flaskges_ecole.eleves.forms import EleveForm

eleves = Blueprint('eleves', __name__)

@eleves.route('/eleve/new', methods=['POST', 'GET'])
@login_required
def new_eleve():
    form = EleveForm()
    if form.validate_on_submit():
       eleve = Eleve(prenom_eleve=form.prenom_eleve.data, nom_eleve=form.nom_eleve.data, sexe=form.sexe.data, user=current_user)
       classe = Classe.query.filter_by(id=form.id_nom_classe.data).first()
       classe.eleves.append(eleve)
       db.session.add(classe)
       db.session.commit()
       flash(' Inscription reussi avec success !','success')
       return redirect(url_for('main.dashbord'))
    classes = Classe.query.all()
    return render_template('eleves/new_eleve.html', form=form, legend='New Eleve', title='New Eleve', classes=classes)

Ges_Ecole/flaskges_ecole/main/routes.py
from flask import render_template, request, Blueprint, redirect, url_for


main = Blueprint('main', __name__)

@main.route('/')
def home():
    return redirect(url_for('users.login'))

@main.route('/dashbord')
def dashbord():
    return render_template('pages/dashbord.html', title='Dashbord')

Ges_Ecole/flaskges_ecole/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskges_ecole import db, bcrypt
from flaskges_ecole.models import User
from flaskges_ecole.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskges_ecole.users.utils import save_picture, send_reset_email


users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
      return redirect(url_for('main.dashbord'))
    form = RegistrationForm()
    if form.validate_on_submit():
      hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
      user = User(username=form.username.data, email=form.email.data, password=hashed_password)
      db.session.add(user)
      db.session.commit()
      flash('Your account has been created ! You are now able to log in','success')
      return redirect(url_for('users.login'))

    return render_template('connexion/register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
      return redirect(url_for('main.dashbord'))
    form = LoginForm()
    if form.validate_on_submit():
      user = User.query.filter_by(email=form.email.data).first()
      if user and bcrypt.check_password_hash(user.password, form.password.data):
        login_user(user, remember=form.remember.data)
        next_page = request.args.get('next')
        return redirect(next_page) if next_page else redirect(url_for('main.dashbord'))
      else:
        flash('Login Unsuccessful. Pleaz check email and password', 'danger')
    return render_template('connexion/login.html', title='Login', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
      if form.picture.data:
        picture_file = save_picture(form.picture.data)
        current_user.image_file = picture_file

      current_user.username = form.username.data
      current_user.email = form.email.data
      db.session.commit()
      flash('Your account has been update !', 'success')
      return redirect(url_for('users.account'))
    elif request.method == 'GET':
      form.username.data = current_user.username
      form.email.data = current_user.email

    image_file = url_for('static', filename='profile_pics/' + current_user.image_file )
    return render_template('connexion/account.html', image_file=image_file, title='Account', form=form)


@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
            .order_by(Post.date_posted.desc())\
            .paginate(page=page, per_page=5)

    return render_template('posts/user_posts.html', title='User Post',posts=posts, user=user)


@users.route('/reset_password', methods=['POST', 'GET'])
def reset_request():
    if current_user.is_authenticated:
      return redirect(url_for('main.home'))

    form = RequestResetForm()
    if form.validate_on_submit():
      user = User.query.filter_by(email=form.email.data).first()
      send_reset_email(user)
      flash('An email has been send with instructions to reset your password ', 'info')
      return redirect(url_for('users.login'))

    return render_template('connexion/reset_request.html', form=form, title='Reset Password')

@users.route('/reset_password/<token>', methods=['POST', 'GET'])
def reset_token(token):
    if current_user.is_authenticated:
      return redirect(url_for('main.home'))

    user = User.verify_reset_token(token)
    if user is None:
      flash('That is an valid or expired token ', 'warning')
      return redirect(url_for('users.reset_request'))

    form = ResetPasswordForm()
    if form.validate_on_submit():
      hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
      user.password = hashed_password
      db.session.commit()
      flash('Your password has been update ! You are now able to log in','success')
      return redirect(url_for('users.login'))
    return render_template('connexion/reset_token.html', form=form, title='Reset Password')

Ges_Ecole/flaskges_ecole/templates/layouts/partials/_card_left.html
<br>
<a href="{{url_for('main.dashbord')}}"  class="btn color-btn btn-info">Tableau de bord</a><br> <br>
<div class="btn-group">
  <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Gestion Inscription
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="{{ url_for('eleves.new_eleve') }}">Nouveau Eleve</a>
    <a class="dropdown-item" href="{{ url_for('classes.search_name_classe') }}">Liste des eleves</a>
  </div>
</div>

Ges_Ecole/flaskges_ecole/templates/layouts/partials/_nav.html
<header class="site-header">
  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
    <div class="container">
      <a class="navbar-brand mr-4" href="{{url_for('main.dashbord')}}">Gestion Ecole</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <ul class="navbar-nav mr-auto">

        </ul>
        <!-- Navbar Right Side -->
        <ul class="navbar-nav">
          {% if current_user.is_authenticated %}
            <li class="nav-item dropdown ">
               <a id="navbarDropdown" class="nav-link dropdown-toggle " href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                 <img src="{{ url_for('static', filename = 'profile_pics/' + current_user.image_file) }}" style="width:50px; height:50px; border-radius:50%">
                 {{ current_user.username }}
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{ url_for('users.account') }}">
                  {{ ('Account') }}
                </a>
                 <a class="dropdown-item" href="{{ url_for('classes.new_classe') }}">
                  {{ ('New Classe') }}
                </a>
                <a class="dropdown-item" href="{{ url_for('users.logout') }}">
                  {{ ('Logout') }}
                </a>
              </div>
            </li>
          {% else %}
            <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
            <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</header>